### ISSUE TITLE
Piratenwiki proposition import

### ISSUE THREAD

**Issue by dpausp** [Piratenpartei/ekklesia-portal#2]
We need a standalone script that imports JSON dumps from the wiki.piratenpartei.de Antragsportal like:

~~~
python import_proposition_json.py --department=Bundesverband WP001.json WP002.json
~~~

Authors should be generated as dummy users.

**Comment by GamesGamble** [comment]
Still needs to do some more work:
 * adding support for more proposition submitter
 * change failed proposition import from exception to skip file with logging message
