### ISSUE TITLE
Add dropdown widget for proposition status

### ISSUE THREAD

**Issue by GamesGamble** [Piratenpartei/ekklesia-portal#36]
* the proposition status field only allows PropositionStatus enum values and therefore, when editing or creating propositions with another value, creates a bug.
 * PropositionStatus.VOTING and higher status needs a proposition voting identifier
   * without it, it causes a bug #11
 * PropositionStatus.FINISHED  needs a voting result (with supported format) in the ballot
   * without it, it shows no voting result in the view (Should be avoided)

**Comment by dpausp** [comment]
I think this is ok for now. There's a select field for the proposition status and invalid states are caught by database constraints. This can only happen to admin which should know what they are doing. Having no voting result is ok.
I cannot reproduce the problem with the missing identifier atm.
